spring.application.name=ProShop
spring.mvc.servlet.path=/api/v1
spring.data.mongodb.uri=mongodb+srv://bob123:bob123@cluster0.kugpsyk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=productDb
